# -*- coding: utf-8 -*-
"""problem1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DjXtkHr5utg807ms_nKKRaLWUnX-8hUi
"""

def isPalindrome(word):

    if(len(word)==0):

        return False

    N = len(word)

    for i in range(0,N//2):

        if(word[i] != word[N-1-i]):

            return False

    return True

#parity check

def parityCheck(number):

    if(number%2==0):

        return True

    else:

        return False

# main

_file = open("/content/input.txt",'r')

_read = _file.readlines()

no_lines = len(_read)

#  count palindrome,not palindrome, parity , not parity

palindrome_count = 0

not_palindrome_count = 0

float_numbers_count = 0

even_parity = 0

odd_parity = 0

#empty list result

result = []

# for loop to loop the files in the _read

for index in _read:

    i = index.split()

    _str=""

    #using try catch 

    try:

        if(isinstance(int(i[0]),float)):

            pass

        else:

            # calling function for parity check

            if(parityCheck(int(i[0]))):

                _str +=str(i[0])+" has even parity and "

                even_parity+=1

            else:

                _str +=str(i[0])+" has odd parity and "

                odd_parity+=1

    #catch any exception error


    except:

        _str +=str(i[0])+" cannot have parity and "

        float_numbers_count+=1

    if(isPalindrome(i[1])):

        _str += str(i[1])+" is a palindrome"

        palindrome_count+=1

    else:

        _str += str(i[1])+" is not a palindrome"

        not_palindrome_count+=1

    result.append(_str)

# output.txt in write mode

output_file = open("output.txt",'w')


for i in result:

    output_file.write(i)

    output_file.write("\n")

# opent the file record.txt in write mode

record_file = open("record.txt","w")

# calculate and write the line to file

record_file.write("Percentage of Odd parity {}%\n".format((odd_parity/no_lines)*100))

record_file.write("Percentage of even parity {}%\n".format((even_parity/no_lines)*100))

record_file.write("Percentage of no  parity {}%\n".format((float_numbers_count/no_lines)*100))

record_file.write("Percentage of Palindrome {}%\n".format((palindrome_count/no_lines)*100))

record_file.write("Percentage of non-Palindrome {}%\n".format((not_palindrome_count/no_lines)*100))

# closing all the files

record_file.close()

output_file.close()

_file.close()