# -*- coding: utf-8 -*-
"""problem4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U4rdwwDELGP-bjAJeFljmtaskQyOwcCW
"""

#A = [[1, 2, 3], 
      [1, 3, 4], 
      [2, 1, 1]]

#B = [[4, 1, 1],
      [5, 2, 1], 
      [6, 1, 1]]

#C  = [[0,0,0],
       [0,0,0],
       [0,0,0]]



#To Multiply A and B matrices
#for i in range(len(A)):
    #for k in range(len(B)):
        #C[i][k] = A[i][k] * B[i][k]

#To Print the matrix
#print("The multiplication of Matrix A and B = ", C)

A = [[1,2,3],  
       [1,3,4],  
       [2,1,1]]  
  
B = [[4,1,1],  
      [5,2,1],  
      [6,1,1]]  
  
C = [[0,0,0],  
               [0,0,0],  
              [0,0,0]]  
  
# iterate through rows of X  
for i in range(len(A)):  
   for j in range(len(B[0])):  
       for k in range(len(B)):  
           C[i][j] += A[i][k] * B[k][j]  
for r in Result:  
   print( r )