# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14_fpmY3JPVlcCw8e8F-NdeKegJRa8_FU
"""

def selectionsort(A):   
    for i in range(len(A)):
        min_idx = i
        for j in range(i+1, len(A)):
            if A[min_idx] > A[j]:
                min_idx = j
        A[i], A[min_idx] = A[min_idx], A[i]
    return A
    


#driver code

#taking input from user 
x,y=map(int,input().split(" "))  

#taking as list input
li=list(map(int,input().split(" ")[:x]))   

#calling the list function 
li=selectionSort(li) 

#print output
print(*li[:y])

