# -*- coding: utf-8 -*-
"""Task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T8loeDaz1Hv0CWTHcrveQcn_UlMIxt9S
"""

a= {
1 : [2],
2 : [3, 4, 5], 
3 : [4, 7, 11],
4 : [],        
5 : [6, 7],    
6 : [7, 8],    
7 : [11],      
8 : [9, 10],   
9 : [10],
10 : [11],
11 : [12],
12 : []
}

visited = []

def dfs_visit(graph, s):
    global visited
    for v in graph[s]:
        if v not in visited:
            visited.append(v)
            dfs_visit(graph, v)


def dfs(graph):
    global visited
    for v in [*graph]:
        if v not in visited:
            visited.append(v)
            dfs_visit(graph,v)

dfs(a)
print(visited)